/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Work Order Management API
 * A comprehensive API for managing work orders, assignments, and customer interactions
 * OpenAPI spec version: 1.0.0
 */

