/* tslint:disable */
/* eslint-disable */
/**
 * Work Order App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemPublic
 */
export interface ItemPublic {
    /**
     * 
     * @type {string}
     * @memberof ItemPublic
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ItemPublic
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ItemPublic
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ItemPublic
     */
    ownerId: string;
    /**
     * 
     * @type {Date}
     * @memberof ItemPublic
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ItemPublic interface.
 */
export function instanceOfItemPublic(value: object): value is ItemPublic {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ItemPublicFromJSON(json: any): ItemPublic {
    return ItemPublicFromJSONTyped(json, false);
}

export function ItemPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'ownerId': json['owner_id'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ItemPublicToJSON(json: any): ItemPublic {
    return ItemPublicToJSONTyped(json, false);
}

export function ItemPublicToJSONTyped(value?: ItemPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'id': value['id'],
        'owner_id': value['ownerId'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

