/* tslint:disable */
/* eslint-disable */
/**
 * Work Order App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemCreate
 */
export interface ItemCreate {
    /**
     * 
     * @type {string}
     * @memberof ItemCreate
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ItemCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ItemCreate interface.
 */
export function instanceOfItemCreate(value: object): value is ItemCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ItemCreateFromJSON(json: any): ItemCreate {
    return ItemCreateFromJSONTyped(json, false);
}

export function ItemCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ItemCreateToJSON(json: any): ItemCreate {
    return ItemCreateToJSONTyped(json, false);
}

export function ItemCreateToJSONTyped(value?: ItemCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

