/* tslint:disable */
/* eslint-disable */
/**
 * Work Order App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemUpdate
 */
export interface ItemUpdate {
    /**
     * 
     * @type {string}
     * @memberof ItemUpdate
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ItemUpdate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the ItemUpdate interface.
 */
export function instanceOfItemUpdate(value: object): value is ItemUpdate {
    return true;
}

export function ItemUpdateFromJSON(json: any): ItemUpdate {
    return ItemUpdateFromJSONTyped(json, false);
}

export function ItemUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ItemUpdateToJSON(json: any): ItemUpdate {
    return ItemUpdateToJSONTyped(json, false);
}

export function ItemUpdateToJSONTyped(value?: ItemUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

