/* tslint:disable */
/* eslint-disable */
/**
 * Work Order App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemPublic } from './ItemPublic';
import {
    ItemPublicFromJSON,
    ItemPublicFromJSONTyped,
    ItemPublicToJSON,
    ItemPublicToJSONTyped,
} from './ItemPublic';

/**
 * 
 * @export
 * @interface ItemsPublic
 */
export interface ItemsPublic {
    /**
     * 
     * @type {Array<ItemPublic>}
     * @memberof ItemsPublic
     */
    data: Array<ItemPublic>;
    /**
     * 
     * @type {number}
     * @memberof ItemsPublic
     */
    count: number;
}

/**
 * Check if a given object implements the ItemsPublic interface.
 */
export function instanceOfItemsPublic(value: object): value is ItemsPublic {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ItemsPublicFromJSON(json: any): ItemsPublic {
    return ItemsPublicFromJSONTyped(json, false);
}

export function ItemsPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemsPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ItemPublicFromJSON)),
        'count': json['count'],
    };
}

export function ItemsPublicToJSON(json: any): ItemsPublic {
    return ItemsPublicToJSONTyped(json, false);
}

export function ItemsPublicToJSONTyped(value?: ItemsPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ItemPublicToJSON)),
        'count': value['count'],
    };
}

