/* tslint:disable */
/* eslint-disable */
/**
 * Work Order App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewPassword
 */
export interface NewPassword {
    /**
     * 
     * @type {string}
     * @memberof NewPassword
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof NewPassword
     */
    newPassword: string;
}

/**
 * Check if a given object implements the NewPassword interface.
 */
export function instanceOfNewPassword(value: object): value is NewPassword {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function NewPasswordFromJSON(json: any): NewPassword {
    return NewPasswordFromJSONTyped(json, false);
}

export function NewPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'newPassword': json['new_password'],
    };
}

export function NewPasswordToJSON(json: any): NewPassword {
    return NewPasswordToJSONTyped(json, false);
}

export function NewPasswordToJSONTyped(value?: NewPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'new_password': value['newPassword'],
    };
}

