/* tslint:disable */
/* eslint-disable */
/**
 * Work Order App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivateUserCreate
 */
export interface PrivateUserCreate {
    /**
     * 
     * @type {string}
     * @memberof PrivateUserCreate
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserCreate
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserCreate
     */
    fullName: string;
    /**
     * 
     * @type {boolean}
     * @memberof PrivateUserCreate
     */
    isVerified?: boolean;
}

/**
 * Check if a given object implements the PrivateUserCreate interface.
 */
export function instanceOfPrivateUserCreate(value: object): value is PrivateUserCreate {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    return true;
}

export function PrivateUserCreateFromJSON(json: any): PrivateUserCreate {
    return PrivateUserCreateFromJSONTyped(json, false);
}

export function PrivateUserCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateUserCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'fullName': json['full_name'],
        'isVerified': json['is_verified'] == null ? undefined : json['is_verified'],
    };
}

export function PrivateUserCreateToJSON(json: any): PrivateUserCreate {
    return PrivateUserCreateToJSONTyped(json, false);
}

export function PrivateUserCreateToJSONTyped(value?: PrivateUserCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'full_name': value['fullName'],
        'is_verified': value['isVerified'],
    };
}

