/* tslint:disable */
/* eslint-disable */
/**
 * Work Order App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePassword
 */
export interface UpdatePassword {
    /**
     * 
     * @type {string}
     * @memberof UpdatePassword
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePassword
     */
    newPassword: string;
}

/**
 * Check if a given object implements the UpdatePassword interface.
 */
export function instanceOfUpdatePassword(value: object): value is UpdatePassword {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function UpdatePasswordFromJSON(json: any): UpdatePassword {
    return UpdatePasswordFromJSONTyped(json, false);
}

export function UpdatePasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePassword {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['current_password'],
        'newPassword': json['new_password'],
    };
}

export function UpdatePasswordToJSON(json: any): UpdatePassword {
    return UpdatePasswordToJSONTyped(json, false);
}

export function UpdatePasswordToJSONTyped(value?: UpdatePassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
    };
}

