/* tslint:disable */
/* eslint-disable */
/**
 * Work Order App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateMe
 */
export interface UserUpdateMe {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateMe
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateMe
     */
    email?: string | null;
}

/**
 * Check if a given object implements the UserUpdateMe interface.
 */
export function instanceOfUserUpdateMe(value: object): value is UserUpdateMe {
    return true;
}

export function UserUpdateMeFromJSON(json: any): UserUpdateMe {
    return UserUpdateMeFromJSONTyped(json, false);
}

export function UserUpdateMeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateMe {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function UserUpdateMeToJSON(json: any): UserUpdateMe {
    return UserUpdateMeToJSONTyped(json, false);
}

export function UserUpdateMeToJSONTyped(value?: UserUpdateMe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'full_name': value['fullName'],
        'email': value['email'],
    };
}

