/* tslint:disable */
/* eslint-disable */
/**
 * Work Order App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPublic } from './UserPublic';
import {
    UserPublicFromJSON,
    UserPublicFromJSONTyped,
    UserPublicToJSON,
    UserPublicToJSONTyped,
} from './UserPublic';

/**
 * 
 * @export
 * @interface UsersPublic
 */
export interface UsersPublic {
    /**
     * 
     * @type {Array<UserPublic>}
     * @memberof UsersPublic
     */
    data: Array<UserPublic>;
    /**
     * 
     * @type {number}
     * @memberof UsersPublic
     */
    count: number;
}

/**
 * Check if a given object implements the UsersPublic interface.
 */
export function instanceOfUsersPublic(value: object): value is UsersPublic {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function UsersPublicFromJSON(json: any): UsersPublic {
    return UsersPublicFromJSONTyped(json, false);
}

export function UsersPublicFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPublic {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(UserPublicFromJSON)),
        'count': json['count'],
    };
}

export function UsersPublicToJSON(json: any): UsersPublic {
    return UsersPublicToJSONTyped(json, false);
}

export function UsersPublicToJSONTyped(value?: UsersPublic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(UserPublicToJSON)),
        'count': value['count'],
    };
}

